// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestLogin.Models
{
    public partial class Book
    {
        public Book()
        {
            BuyedBook = new HashSet<BuyedBook>();
        }

        /// <summary>
        /// 책 아이디
        /// </summary>
        [Key]
        public int BookId { get; set; }
        /// <summary>
        /// 책 이름
        /// </summary>
        [StringLength(50)]
        public string BookName { get; set; }
        /// <summary>
        /// 국제 표준 도서번호
        /// </summary>
        [Column("ISBN")]
        [StringLength(50)]
        public string Isbn { get; set; }

        [InverseProperty("Book")]
        public virtual ICollection<BuyedBook> BuyedBook { get; set; }
    }
}