// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestLogin.Models
{
    public partial class BuyedBook
    {
        [Key]
        [Column("NID")]
        public int Nid { get; set; }
        [Required]
        [StringLength(20)]
        public string UserId { get; set; }
        public int BookId { get; set; }

        [ForeignKey("BookId")]
        [InverseProperty("BuyedBook")]
        public virtual Book Book { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("BuyedBook")]
        public virtual User User { get; set; }
    }
}