// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestLogin.Models
{
    public partial class User
    {
        public User()
        {
            BuyedBook = new HashSet<BuyedBook>();
        }

        /// <summary>
        /// 유저ID
        /// </summary>
        [Key]
        [Column("ID")]
        [StringLength(20)]
        public string Id { get; set; }
        /// <summary>
        /// 패스워드
        /// </summary>
        [Required]
        [Column("PW")]
        [StringLength(20)]
        public string Pw { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<BuyedBook> BuyedBook { get; set; }
    }
}